# Generated by Django 4.2.4 on 2023-09-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='question_text',
        ),
        migrations.AddField(
            model_name='phase',
            name='web_text',
            field=models.CharField(default='default', max_length=20000),
        ),
        migrations.AlterField(
            model_name='phase',
            name='title_text',
            field=models.CharField(default='Phase', max_length=200),
        ),
    ]
