# Generated by Django 4.2.4 on 2023-09-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0002_remove_phase_question_text_phase_web_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='weight',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
