# Generated by Django 4.2.4 on 2023-09-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0003_phase_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='pub_date',
        ),
    ]
