# Generated by Django 4.2.4 on 2023-09-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0004_remove_phase_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='id',
        ),
        migrations.AlterField(
            model_name='phase',
            name='weight',
            field=models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
