# Generated by Django 4.2.4 on 2023-09-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0005_remove_phase_id_alter_phase_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='weight',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
