# Generated by Django 4.2.4 on 2023-09-05 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0006_phase_id_alter_phase_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
