# Generated by Django 4.2.4 on 2023-09-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0008_alter_phase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='web_text',
            field=models.CharField(default='None', max_length=20000),
        ),
    ]
