# Generated by Django 4.2.4 on 2023-12-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0010_phase_phase_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['weight']},
        ),
    ]
