# Generated by Django 4.2.4 on 2023-12-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0011_alter_phase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={},
        ),
    ]
