# Generated by Django 4.2.4 on 2024-04-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProgress', '0012_alter_phase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['weight']},
        ),
    ]
