# Generated by Django 4.2.4 on 2023-12-15 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(default=0)),
                ('week_webpage_source', models.CharField(default='test', max_length=50)),
                ('week_title', models.CharField(default='test', max_length=300)),
                ('week_description', models.CharField(default='test', max_length=300)),
                ('quiz_description', models.CharField(default='None', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['week_num'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Friday')], default=(1, 'Monday'), max_length=50)),
                ('day_webpage_source', models.CharField(default='test', max_length=50)),
                ('day_description', models.CharField(default='test', max_length=300)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Math_161.week')),
            ],
        ),
    ]
