# Generated by Django 4.2.4 on 2023-12-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0002_alter_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='quiz_Boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Friday')], default=(1, 'Monday')),
        ),
    ]
