# Generated by Django 4.2.4 on 2023-12-16 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0003_week_quiz_boolean_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
