# Generated by Django 4.2.4 on 2023-12-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0006_alter_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_webpage_source',
        ),
    ]
