# Generated by Django 4.2.4 on 2023-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0008_day_day_worksheet_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_worksheet_source',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
