# Generated by Django 4.2.4 on 2023-12-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0010_alter_week_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_worksheet_source',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
