# Generated by Django 4.2.4 on 2023-12-17 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0011_alter_day_day_worksheet_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_num', models.IntegerField(default=0)),
                ('quiz_prepsheet_source', models.CharField(default='#', max_length=100)),
                ('quiz_here', models.BooleanField(default=False)),
                ('quiz_here_source', models.CharField(default='#', max_length=100)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='Math_161.week')),
            ],
        ),
    ]
