# Generated by Django 4.2.4 on 2023-12-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0012_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
