# Generated by Django 4.2.4 on 2023-12-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0013_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_Slides_Boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='day_Slides_Source',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
