# Generated by Django 4.2.4 on 2024-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0014_day_day_slides_boolean_day_day_slides_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Rubric_source',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
