# Generated by Django 4.2.4 on 2024-01-14 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0015_quiz_rubric_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='release_answers_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
