# Generated by Django 4.2.4 on 2024-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0016_quiz_release_answers_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_answer_source',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
