# Generated by Django 4.2.4 on 2024-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0017_quiz_quiz_answer_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['quiz_num']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
