# Generated by Django 4.2.4 on 2024-04-10 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0018_alter_quiz_options_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
