# Generated by Django 4.2.4 on 2024-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_161', '0019_alter_week_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_Slides_Source',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
