# Generated by Django 4.2.4 on 2023-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0002_week_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week_worksheet',
            field=models.CharField(default='Not described', max_length=100),
        ),
    ]
