# Generated by Django 4.2.4 on 2023-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0003_week_week_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week_quiz_title',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
