# Generated by Django 4.2.4 on 2023-10-26 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0004_week_week_quiz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workshop_location', models.CharField(default='test', max_length=100)),
                ('weight', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
