# Generated by Django 4.2.4 on 2023-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0006_workshop_str_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='str_return',
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_description',
            field=models.CharField(default='Not described', max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_webpage',
            field=models.CharField(default='Not described', max_length=100),
        ),
    ]
