# Generated by Django 4.2.4 on 2023-10-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0007_remove_workshop_str_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_title',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
