# Generated by Django 4.2.4 on 2023-11-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0008_workshop_workshop_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['weight']},
        ),
    ]
