# Generated by Django 4.2.4 on 2023-11-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Math340', '0009_alter_week_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['weight']},
        ),
    ]
