# Generated by Django 4.2.4 on 2023-11-21 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_location', models.CharField(default='test', max_length=100)),
                ('weight', models.PositiveBigIntegerField(default=0)),
                ('topic_webpage', models.CharField(default='Not described', max_length=100)),
                ('topic_description', models.CharField(default='Not described', max_length=100)),
                ('topic_title', models.CharField(default='test', max_length=100)),
            ],
        ),
    ]
