# Generated by Django 4.2.4 on 2023-12-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['weight']},
        ),
    ]
